# Model arguments
model_name_or_path: /checkpoints/postsft-model-v2
model_revision: main
tokenizer_name_or_path: /checkpoints/postsft-model-v2 # Custom tokenizer with <|im_start|> and <|im_end|> tokens
torch_dtype: bfloat16
# use_flash_attention_2: true

# Data training arguments
dataset_mixer:
  /data/input_sanitization/full.hf: 1.0

dataset_configs:
- all

dataset_splits:
- train
- test
preprocessing_num_workers: 36

# SFT trainer config
bf16: true
do_eval: true
evaluation_strategy: steps
eval_steps: 200
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
# hub_model_id: smollm2-1.7B-sft
# hub_strategy: every_save
learning_rate: 1.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048 # 8192
max_steps: -1
num_train_epochs: 3
output_dir: /checkpoints/postsft-input-sanitizer-wildjailbreak-tournament-codeforces/run_3e-04_2
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
push_to_hub: false
remove_unused_columns: true
report_to:
- tensorboard
- wandb
save_strategy: "epoch"
save_total_limit: 3
seed: 42
warmup_ratio: 0.1
dataset_text_field: "text"
packing: false